export type MatchObject = {
  idmatch: string;
  idcompetition: string;
  round: string;
  idorigin: string;
  idteam_home: string;
  team_name_home: string;
  score_home: string;
  idrace_home: string;
  logo_home: string;
  idteam_away: string;
  team_name_away: string;
  idrace_away: string;
  score_away: string;
  logo_away: string;
  idcoach_home: string;
  coach_name_home: string;
  idcoach_away: string;
  coach_name_away: string;
  schedule_origin_uid: string;
  userdate: string;
  userdate_changed: string;
};

export type StandingObject = {
  idstanding: string;
  idcompetition: string;
  ranking: string;
  points: string;
  sorting: string;
  active: string;
  wins: string;
  draws: string;
  losses: string;
  td: string;
  td_opp: string;
  td_diff: string;
  cas: string;
  cas_opp: string;
  cas_diff: string;
  concedes: string;
  team_value: string;
  kills: string;
  position: string;
  gp: string;
  idteam: string;
  idrace: string;
  team_name: string;
  logo: string;
  twitch: string;
  youtube: string;
  idcoach: string;
  coach_name: string;
};
